import { useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import AuthHero from "../components/AuthHero";
import Button from "../components/ui/Button";
import InputField from "../components/ui/InputField";
import { resetPassword, getErrorMessage } from "../services/api";
import toast from "react-hot-toast";

function ResetPasswordPage() {
  const { token } = useParams();
  const navigate = useNavigate();
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (event) => {
    event.preventDefault();
    if (password !== confirmPassword) {
      toast.error("Passwords must match.");
      return;
    }
    setLoading(true);

    try {
      await resetPassword(token, { password });
      toast.success("Password reset successfully. Log in with your new password.");
      navigate("/login");
    } catch (error) {
      toast.error(getErrorMessage(error, "Unable to reset password."));
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="container-shell py-10 sm:py-14">
      <div className="grid gap-8 lg:grid-cols-[1.05fr_0.95fr]">
        <AuthHero
          title="Choose a new password."
          subtitle="Use the token sent to your email or generated by the reset flow." 
          stats={[
            { label: "Secure flow", value: "AES-safe" },
            { label: "Expires in", value: "1 hour" },
            { label: "Ready to use", value: "Immediately" },
          ]}
        />
        <div className="glass-panel p-8 md:p-10">
          <h2 className="font-display text-3xl font-bold">Reset password</h2>
          <p className="mt-3 text-sm text-slate-500 dark:text-slate-400">
            Enter a new password for your account. Your reset token is included in the URL.
          </p>
          <form className="mt-8 space-y-5" onSubmit={handleSubmit}>
            <InputField label="New password" name="password" type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="New password" required />
            <InputField label="Confirm password" name="confirmPassword" type="password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} placeholder="Confirm password" required />
            <Button type="submit" loading={loading} className="w-full">Reset password</Button>
          </form>
        </div>
      </div>
    </div>
  );
}

export default ResetPasswordPage;
